### ISSUE TITLE
Final Review - Wiki - User Documentation

### ISSUE THREAD

**Issue by wryenmeek** [adhocteam/ca-alert#293]
https://github.com/adhocteam/ca-alert/wiki/User-Documentation

1. Spelling & Grammar
2. Content
- does it make sense? 
- Is there anything missing?
- Are there any Acronyms or Shorthand that need to be unpacked?
- Is everything that can be linked to, linked correctly?

**Comment by leannammiller** [comment]
LGTM

**Comment by wryenmeek** [comment]
updated markdown styling
